### ISSUE TITLE
A novice's question on configuring atmo

### ISSUE THREAD

**Issue by BillBaar** [cqframework/ecqm-content-r4-2021#1]
Not an issue but rather a reflection on my new ness.  I have atom configured and I can run the BCE cql here but I get this warning:Running tests.
No tests found at /Users/bill.baar/Desktop/myCQL\ecqm-content-r4-2021/input/tests. Evaluation may fail if data is required.
Terminology path: /Users/bill.baar/Desktop/myCQL\ecqm-content-r4-2021/input/vocabulary/valueset

and null results of course... how do I get inside atom and change these paths?  And once I change which sample data should I copy in to them?
thanks

**Comment by BillBaar** [comment]
ok, we figured this out:

CQL
In the cql folder, place all the CQL for the measure, including any included libraries.  For the BCS-E measure, that would be all the CQL files in the cql and libraryCql folders - copy those into the cql folder in your project.

Tests
Test folders have to be name according to the CQL that is running.  The top level subfolder needs to be named <library>-<version>.  For example in the BCS-E CQL the first line is: library BCSE_HEDIS_MY2022 version '1.0.0'
So the folder name needs to be BCSE_HEDIS_MY2022-1.0.0.  Under that folder needs to be a folder for each patient, with the patient id as the folder name.   

Vocabulary
In the vocabulary folder create subfolders codesystem and valueset.  For the BCS-E measure, that would be all the JSON files in the valuesets folder.  There are no additional codesystems defined for BCS-E.

And the above seems to get us moving

**Comment by p9g** [comment]
See also https://github.com/cqframework/atom_cql_support/blob/master/README.md#using-the-cql-support-in-atom
