### ISSUE TITLE
CDS125 v0.0.009 does not bundle

### ISSUE THREAD

**Issue by bryantaustin13** [cqframework/ecqm-content-r4-2021#11]
CMS125 v 0.0.009 does not bundle correctly.  The other libraries are not included in the bundle produced

**Comment by bryantaustin13** [comment]
Due to this(?) the tests for denom in BreastCancer return:
"Failed to call access method: java.lang.NoSuchMethodError: 'org.hl7.elm.r1.ValueSetRef org.hl7.elm.r1.AnyInValueSet.getValueset()'"
ValueSetRef appears to be only found in HEDIS and NCQA measures, so I am puzzled as to why it shows up for BreastCancer

**Comment by brynrhodes** [comment]
This issue should be addressed by the 1.5.6 translator release (and downstream releases of the engine, tooling, evaluator, ruler, and vscode and atom plugins).
